name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install grpcio grpcio-tools pytest

    - name: Generate gRPC stubs
      run: |
         python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. hello.proto


    - name: Run tests
      run: |
        pytest
